# async/await 如果有变方法执行出错该怎么办？（百度一面 2020）

既优雅又DRY的一种方法是：对 await 处理的 promise 方法进行封装，每次使用 await 时都调用这个 awaitWrap 方法将错误信息提取出来

```js
const awaitWrap = (promise) => {
  return promise.then((data) => [null, data]).catch((err) => [err, null])
}

const [err, data] = await awaitWrap(fetchData())
console.log('err', err)
console.log('data', data)
```

参考：http://www.manongjc.com/article/49918.html 